[package]
name = "nulu2d_testbed"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nulu2d = { path = "../crate_nulu2d" }
ggez = "0.5"
